baseURL: "https://arnold.pe"
languageCode: "es-us"
title: "Arnold Campos"
pygmentsstyle: "monokai"
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "https://github.com/RoyCampos/Template-pe"
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
